# Generated by Django 5.2.8 on 2025-11-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre jugador')),
                ('document', models.CharField(max_length=50, verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de intento')),
                ('current_question_number', models.PositiveIntegerField(default=1)),
                ('max_reached_question', models.PositiveIntegerField(default=0)),
                ('current_prize', models.PositiveIntegerField(default=0)),
                ('finished_reason', models.CharField(blank=True, choices=[('WIN', 'Ganó'), ('LOSE', 'Perdió'), ('TIME', 'Tiempo agotado'), ('QUIT', 'Abandono'), (None, 'En juego')], max_length=10, null=True, verbose_name='Motivo de finalización')),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto de la pregunta')),
                ('option_a', models.CharField(max_length=255, verbose_name='Opción A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Opción B')),
                ('option_c', models.CharField(max_length=255, verbose_name='Opción C')),
                ('option_d', models.CharField(max_length=255, verbose_name='Opción D')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Opción correcta')),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Media'), ('HARD', 'Difícil')], default='EASY', max_length=10, verbose_name='Dificultad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
        ),
    ]
