# Generated by Django 5.2.8 on 2025-11-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameattempt',
            name='fifty_disabled_options',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='used_5050',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='used_friend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='used_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='used_switch',
            field=models.BooleanField(default=False),
        ),
    ]
