# Generated by Django 5.2.8 on 2025-11-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_gameattempt_fifty_disabled_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='juego.gameattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.question')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
