# Generated by Django 5.2.8 on 2025-11-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_attemptquestion'),
        ('juego', '0004_cargar_preguntas'),
    ]

    operations = [
    ]
